### ISSUE TITLE
rasa visualize 数据可视化时报policy找不到的错误

### ISSUE THREAD

**Issue by ForgetThatNight** [jiangdongguo/ChitChatAssistant#13]
Traceback (most recent call last):
  File "/home/sundali/anaconda3/envs/chatbot/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/sundali/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/sundali/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/cli/visualize.py", line 38, in visualize_stories
    args.config, args.domain, args.stories, args.nlu, args.out, args.max_history
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/sundali/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/visualize.py", line 24, in visualize
    policies = config.load(config_path)
  File "/home/sundali/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/config.py", line 28, in load
    return PolicyEnsemble.from_dict(config_data)
  File "/home/sundali/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/policies/ensemble.py", line 273, in from_dict
    "You didn't define any policies. "
rasa.core.policies.ensemble.InvalidPolicyConfig: You didn't define any policies. Please define them under 'policies:' in your policy configuration file.

**Comment by jiangdongguo** [comment]
Please define them under 'policies:' in your policy configuration file.
